"""Create websites table

Revision ID: 04b6f7c576bb
Revises: dbef1ae19db7
Create Date: 2026-03-12 22:51:11.384988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b6f7c576bb'
down_revision = 'dbef1ae19db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websites')
    # ### end Alembic commands ###
