"""add cms_data to websites

Revision ID: 316920690928
Revises: dde0531edb19
Create Date: 2026-04-02 10:46:56.127393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316920690928'
down_revision = 'dde0531edb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cms_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_column('cms_data')

    # ### end Alembic commands ###
