"""initial migration

Revision ID: dbef1ae19db7
Revises: 
Create Date: 2026-03-12 15:22:03.740301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbef1ae19db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_fa_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
