"""add updated_at to websites

Revision ID: fb382c7f5ac7
Revises: 2f8ceb70be82
Create Date: 2026-03-24 12:26:32.097326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb382c7f5ac7'
down_revision = '2f8ceb70be82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
